<template>
  <div class="about-page">
    <Placeholder 
      title="Header"
    />
    <Placeholder 
      title="Hero"
      :aspect-ratio="2"
    />
    <Placeholder 
      title="About"
      :aspect-ratio="2"
    />
    <Placeholder 
      title="Footer"
      :aspect-ratio="3"
    />
  </div>
</template>